version: "2"

services:
  dev_db:
    image: "postgres:12-alpine"
    environment:
      - POSTGRES_PASSWORD=guest
      - POSTGRES_USER=guest
      - POSTGRES_DB=example
    ports:
      - "5432:5432"
