name: Test app

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    container: python:3.9-slim

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: cars
          POSTGRES_USER: guest
          POSTGRES_PASSWORD: guest
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_HOST: postgres
      DB_NAME: cars
      DB_USER: guest
      DB_PASSWORD: guest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install black
          pip install -r requirements/all.txt
      
      - name: Lint with black
        run: black --check cars
      
      - name: Test app
        run: pytest
